from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

import pytest
from git.exc import GitCommandError
from git.repo import Repo
from pydantic import HttpUrl, ValidationError

from locloc import loc
from locloc.loc import Total, TotalByLanguageDict, get_loc_stats, get_loc_svg

SVG_NS = "{http://www.w3.org/2000/svg}"
PLACEHOLDER_URL = HttpUrl("https://example.invalid/owner/repo")


@pytest.fixture
def clone_calls(monkeypatch: pytest.MonkeyPatch, sample_repo: Path) -> list[dict[str, Any]]:
    """Redirect ``Repo.clone_from`` to the local :func:`sample_repo`, recording every call."""
    calls: list[dict[str, Any]] = []
    real_clone_from = Repo.clone_from

    def fake_clone_from(*, url: str, **kwargs: Any) -> Repo:  # noqa: ANN401
        calls.append({"url": url, **kwargs})
        return real_clone_from(url=sample_repo.as_uri(), **kwargs)

    monkeypatch.setattr(loc.Repo, "clone_from", staticmethod(fake_clone_from))
    return calls


def _legend_labels(svg: bytes) -> list[str]:
    """Series labels of a pygal chart, in the order they were added."""
    root = ET.fromstring(svg)  # noqa: S314 - locally generated by pygal
    return [
        text.text or ""
        for group in root.iter(f"{SVG_NS}g")
        if group.get("class") == "legends"
        for text in group.iter(f"{SVG_NS}text")
    ]


class TestTotal:
    def test_accepts_plain_dict(self) -> None:
        payload = {"lines": 10, "blanks": 2, "code": 6, "files": 1, "comments": 2}

        total = Total.model_validate(payload)

        assert total.model_dump() == payload

    def test_rejects_missing_field(self) -> None:
        with pytest.raises(ValidationError):
            Total.model_validate({"lines": 10, "blanks": 2, "code": 6, "files": 1})

    def test_rejects_non_numeric_value(self) -> None:
        with pytest.raises(ValidationError):
            Total.model_validate({"lines": "many", "blanks": 2, "code": 6, "files": 1, "comments": 2})


class TestTotalByLanguageDict:
    def test_preserves_insertion_order(self) -> None:
        payload = {name: {"lines": 1, "blanks": 0, "code": 1, "files": 1, "comments": 0} for name in ("C", "A", "B")}
        assert list(TotalByLanguageDict.model_validate(payload).root) == ["C", "A", "B"]

    def test_round_trips_through_model_dump(self, stats: TotalByLanguageDict) -> None:
        assert TotalByLanguageDict.model_validate(stats.model_dump()) == stats


class TestGetLocStats:
    def test_reports_every_language_in_the_repository(self, clone_calls: list[dict[str, Any]]) -> None:
        result, total = get_loc_stats(PLACEHOLDER_URL)

        assert len(clone_calls) == 1
        assert set(result.root) >= {"Python", "JavaScript"}
        assert result.root["Python"].code > 0
        assert result.root["JavaScript"].code > 0
        assert isinstance(total, Total)

    @pytest.mark.usefixtures("clone_calls")
    def test_total_aggregates_the_per_language_report(self) -> None:
        result, total = get_loc_stats(PLACEHOLDER_URL)

        assert total.files == sum(entry.files for entry in result.root.values())
        assert total.code == sum(entry.code for entry in result.root.values())
        assert total.lines == sum(entry.lines for entry in result.root.values())
        assert total.lines == total.code + total.blanks + total.comments

    @pytest.mark.usefixtures("clone_calls")
    def test_languages_are_sorted_by_lines_descending(self) -> None:
        result, _total = get_loc_stats(PLACEHOLDER_URL)

        line_counts = [entry.lines for entry in result.root.values()]
        assert line_counts == sorted(line_counts, reverse=True)

    def test_clones_a_single_shallow_branch(self, clone_calls: list[dict[str, Any]]) -> None:
        get_loc_stats(PLACEHOLDER_URL)

        call = clone_calls[0]
        assert call["url"] == str(PLACEHOLDER_URL)
        assert call["depth"] == 1
        assert call["single_branch"] is True
        assert call["kill_after_timeout"] == pytest.approx(30.0)

    def test_default_branch_is_requested_as_none(self, clone_calls: list[dict[str, Any]]) -> None:
        get_loc_stats(PLACEHOLDER_URL)

        assert clone_calls[0]["branch"] is None

    def test_branch_selects_a_different_revision(self, clone_calls: list[dict[str, Any]]) -> None:
        default, _ = get_loc_stats(PLACEHOLDER_URL)
        other, _ = get_loc_stats(PLACEHOLDER_URL, "other")

        assert clone_calls[1]["branch"] == "other"
        assert other.root["Python"].files == default.root["Python"].files + 1
        assert other.root["Python"].code > default.root["Python"].code

    @pytest.mark.usefixtures("clone_calls")
    def test_unknown_branch_raises_git_command_error(self) -> None:
        with pytest.raises(GitCommandError):
            get_loc_stats(PLACEHOLDER_URL, "no-such-branch")

    @pytest.mark.usefixtures("clone_calls")
    def test_clone_directory_is_removed(self) -> None:
        get_loc_stats(PLACEHOLDER_URL)

        assert list(Path().glob("tmp_*")) == []

    @pytest.mark.usefixtures("clone_calls")
    def test_clone_directory_is_removed_after_failure(self) -> None:
        with pytest.raises(GitCommandError):
            get_loc_stats(PLACEHOLDER_URL, "no-such-branch")

        assert list(Path().glob("tmp_*")) == []

    def test_is_wrapped_in_a_timeout(self) -> None:
        assert hasattr(get_loc_stats, "__wrapped__")


class TestGetLocSvg:
    def test_renders_a_parseable_svg_document(self, stats: TotalByLanguageDict) -> None:
        svg = get_loc_svg(stats)

        assert isinstance(svg, bytes)
        root = ET.fromstring(svg)  # noqa: S314 - locally generated by pygal
        assert root.tag == f"{SVG_NS}svg"

    def test_includes_the_chart_title(self, stats: TotalByLanguageDict) -> None:
        assert b"LOC by language" in get_loc_svg(stats)

    def test_series_are_sorted_by_code_descending(self, stats: TotalByLanguageDict) -> None:
        assert _legend_labels(get_loc_svg(stats)) == ["Python", "JavaScript"]

    def test_languages_without_code_are_dropped(self, stats: TotalByLanguageDict) -> None:
        assert "Markdown" not in _legend_labels(get_loc_svg(stats))

    def test_empty_statistics_still_render(self) -> None:
        svg = get_loc_svg(TotalByLanguageDict.model_validate({}))

        assert _legend_labels(svg) == []
        assert b"LOC by language" in svg

    def test_all_languages_empty_renders_no_series(self) -> None:
        stats = TotalByLanguageDict.model_validate(
            {"Text": {"lines": 5, "blanks": 5, "code": 0, "files": 1, "comments": 0}},
        )

        assert _legend_labels(get_loc_svg(stats)) == []

    @pytest.mark.usefixtures("clone_calls")
    def test_renders_real_statistics(self) -> None:
        result, _total = get_loc_stats(PLACEHOLDER_URL)

        assert set(_legend_labels(get_loc_svg(result))) >= {"Python", "JavaScript"}
